version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/samples/node/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/test/wrangler/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/test/playwright/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/test/fastly/"
    schedule:
      interval: "daily"
