name: bun CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

defaults:
  run:
    working-directory: ./test/runtimes/bun

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno bundle ../../../mod.ts src/bhttp.js
      - uses: antongolub/action-setup-bun@v1
        with:
          bun-version: 0.4
      - name: Run test
        run: |
          nohup bun src/index.js &
          sleep 3
          deno test bhttp.spec.ts --allow-net