name: bun CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: actions/setup-node@v3
        with:
          node-version: v18.x
      - run: deno bundle mod.ts test/bun/src/bhttp.js
      - uses: antongolub/action-setup-bun@v1
        with:
          bun-version: 0.4
      - name: Run test
        working-directory: ./test/bun
        run: |
          nohup bun src/index.js &
          sleep 3
          deno test bhttp.spec.ts --allow-net