name: bun CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        bun-version: [0.6.x, 0.7.x, 0.8.x, 1.x]

    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: antongolub/action-setup-bun@v1
        with:
          bun-version: ${{ matrix.bun-version }}
      - name: Run dnt
        run: deno run -A dnt.ts 0.0.0
      - name: Run npm pack
        working-directory: ./npm
        run: npm pack
      - name: Run test
        working-directory: ./test/runtimes/bun
        run: |
          bun install
          nohup bun run src/index.ts &
          sleep 3
          deno test bhttp.spec.ts --allow-net --config ../../../deno.json