name: Cloudflare Workers CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

defaults:
  run:
    working-directory: ./test/runtimes/cloudflare

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: actions/setup-node@v3
        with:
          node-version: v18.x
      - run: deno bundle ../../../mod.ts src/bhttp.js
      - name: Run test
        run: |
          npm install
          nohup npm start &
          sleep 3
          deno test bhttp.spec.ts --allow-net
