name: fastly/js-compute CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

defaults:
  run:
    working-directory: ./test/fastly

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno bundle ../../mod.ts src/bhttp.js
      - uses: fastly/compute-actions/setup@v2
        env:
          FASTLY_API_TOKEN: ${{ secrets.FASTLY_API_TOKEN }}
      - name: Run test
        run: |
          npm install
          nohup fastly compute serve &
          sleep 20
          deno test bhttp.spec.ts --allow-net
